<?php
// Automatically Generated by TestLink Installer - Tue, 15 Jul 25 09:37:34 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'admin');
define('DB_PASS', 'admin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
